
// Generated by Cadence Genus(TM) Synthesis Solution 19.10-p002_1
// Generated on: Jun 12 2023 19:01:49 MSK (Jun 12 2023 16:01:49 UTC)

// Verification Directory fv/ALU_top 

module ALU_top(clk, res, A, B, out, tvalid, tready);
  input clk, res, A, B, tvalid;
  output out, tready;
  wire clk, res, A, B, tvalid;
  wire out, tready;
  wire [15:0] dut_A_dout;
  wire [15:0] parall_A;
  wire [4:0] dut_B_cnt;
  wire [15:0] dut_B_dout;
  wire [15:0] parall_B;
  wire [3:0] dut_div_fraction_cnt;
  wire [9:0] dut_div_fraction_reg_quotient;
  wire [9:0] fraction;
  wire [9:0] dut_div_fraction_remains;
  wire [3:0] dut_out_cnt;
  wire [15:0] dut_out_dout;
  wire [4:0] exponent;
  wire [15:0] divisible;
  wire [15:0] divider;

  wire dut_comparator_n_1942, dut_comparator_n_1943,
       dut_comparator_n_1946, dut_comparator_n_1947,
       dut_comparator_n_1948, dut_comparator_n_1949,
       dut_comparator_n_1950, dut_comparator_n_1951;
  wire dut_comparator_n_1952, dut_comparator_n_1953,
       dut_comparator_n_1954, dut_comparator_n_1957,
       dut_comparator_n_1958, dut_comparator_n_1959,
       dut_comparator_n_1960, dut_comparator_n_1961;
  wire dut_comparator_n_1962, dut_comparator_n_1965,
       dut_comparator_n_1968, dut_comparator_n_1971,
       dut_comparator_n_1974, dut_comparator_n_1977,
       dut_comparator_n_1978, dut_comparator_n_1989;
  wire dut_comparator_n_1990, dut_comparator_n_2001,
       dut_comparator_n_2003, dut_comparator_n_2004,
       dut_comparator_n_2006, dut_comparator_n_2007,
       dut_comparator_n_2008, dut_comparator_n_2011;
  wire dut_comparator_n_2013, dut_comparator_n_2014,
       dut_comparator_n_2015, dut_comparator_n_2016,
       dut_comparator_n_2020, dut_comparator_n_2022,
       dut_comparator_n_2024, dut_comparator_n_2025;
  wire dut_comparator_n_2028, dut_comparator_n_2031,
       dut_comparator_n_2032, dut_comparator_n_2035,
       dut_comparator_n_2039, dut_comparator_n_2040,
       dut_comparator_n_2041, dut_comparator_n_2042;
  wire dut_comparator_n_2043, dut_comparator_n_2051,
       dut_comparator_n_2053, dut_comparator_n_2056,
       dut_comparator_n_2058, dut_comparator_n_2062,
       dut_comparator_n_2065, dut_comparator_n_2066;
  wire dut_comparator_n_2068, dut_comparator_n_2071,
       dut_comparator_n_2073, dut_comparator_n_2074,
       dut_comparator_n_2081, dut_comparator_n_2082,
       dut_comparator_n_2083, dut_comparator_n_2084;
  wire dut_comparator_n_2085, dut_comparator_n_2087,
       dut_comparator_n_2088, dut_comparator_n_2089,
       dut_comparator_n_2090, dut_comparator_n_2091,
       dut_comparator_n_2092, dut_comparator_n_2093;
  wire dut_comparator_n_2094, dut_comparator_n_2102,
       dut_comparator_n_2103, dut_comparator_n_2104,
       dut_comparator_n_2105, dut_comparator_n_2106,
       dut_comparator_n_2107, dut_comparator_n_2108;
  wire dut_comparator_n_2109, dut_comparator_n_2110,
       dut_comparator_n_2111, dut_comparator_n_2112,
       dut_comparator_n_2113, dut_comparator_n_2114,
       dut_comparator_n_2124, dut_comparator_n_2126;
  wire dut_comparator_n_2131, dut_comparator_n_2180,
       dut_comparator_n_2181, load, load1, load_done, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, ready, ready_stop, ready_stop1, sign;
  SDFFRHQX1 \dut_A_dout_reg[0] (.RN (res), .CK (clk), .D
       (dut_A_dout[0]), .SI (A), .SE (tvalid), .Q (dut_A_dout[0]));
  SDFFRHQX1 \dut_A_dout_reg[1] (.RN (res), .CK (clk), .D
       (dut_A_dout[1]), .SI (dut_A_dout[0]), .SE (tvalid), .Q
       (dut_A_dout[1]));
  SDFFRHQX1 \dut_A_dout_reg[2] (.RN (res), .CK (clk), .D
       (dut_A_dout[2]), .SI (dut_A_dout[1]), .SE (tvalid), .Q
       (dut_A_dout[2]));
  SDFFRHQX1 \dut_A_dout_reg[3] (.RN (res), .CK (clk), .D
       (dut_A_dout[3]), .SI (dut_A_dout[2]), .SE (tvalid), .Q
       (dut_A_dout[3]));
  SDFFRHQX1 \dut_A_dout_reg[4] (.RN (res), .CK (clk), .D
       (dut_A_dout[4]), .SI (dut_A_dout[3]), .SE (tvalid), .Q
       (dut_A_dout[4]));
  SDFFRHQX1 \dut_A_dout_reg[5] (.RN (res), .CK (clk), .D
       (dut_A_dout[5]), .SI (dut_A_dout[4]), .SE (tvalid), .Q
       (dut_A_dout[5]));
  SDFFRHQX1 \dut_A_dout_reg[6] (.RN (res), .CK (clk), .D
       (dut_A_dout[6]), .SI (dut_A_dout[5]), .SE (tvalid), .Q
       (dut_A_dout[6]));
  SDFFRHQX1 \dut_A_dout_reg[7] (.RN (res), .CK (clk), .D
       (dut_A_dout[7]), .SI (dut_A_dout[6]), .SE (tvalid), .Q
       (dut_A_dout[7]));
  SDFFRHQX1 \dut_A_dout_reg[8] (.RN (res), .CK (clk), .D
       (dut_A_dout[8]), .SI (dut_A_dout[7]), .SE (tvalid), .Q
       (dut_A_dout[8]));
  SDFFRHQX1 \dut_A_dout_reg[9] (.RN (res), .CK (clk), .D
       (dut_A_dout[9]), .SI (dut_A_dout[8]), .SE (tvalid), .Q
       (dut_A_dout[9]));
  SDFFRHQX1 \dut_A_dout_reg[10] (.RN (res), .CK (clk), .D
       (dut_A_dout[10]), .SI (dut_A_dout[9]), .SE (tvalid), .Q
       (dut_A_dout[10]));
  SDFFRHQX1 \dut_A_dout_reg[11] (.RN (res), .CK (clk), .D
       (dut_A_dout[11]), .SI (dut_A_dout[10]), .SE (tvalid), .Q
       (dut_A_dout[11]));
  SDFFRHQX1 \dut_A_dout_reg[12] (.RN (res), .CK (clk), .D
       (dut_A_dout[12]), .SI (dut_A_dout[11]), .SE (tvalid), .Q
       (dut_A_dout[12]));
  SDFFRHQX1 \dut_A_dout_reg[13] (.RN (res), .CK (clk), .D
       (dut_A_dout[13]), .SI (dut_A_dout[12]), .SE (tvalid), .Q
       (dut_A_dout[13]));
  SDFFRHQX1 \dut_A_dout_reg[14] (.RN (res), .CK (clk), .D
       (dut_A_dout[14]), .SI (dut_A_dout[13]), .SE (tvalid), .Q
       (dut_A_dout[14]));
  SDFFRHQX1 \dut_A_dout_reg[15] (.RN (res), .CK (clk), .D
       (dut_A_dout[15]), .SI (dut_A_dout[14]), .SE (tvalid), .Q
       (dut_A_dout[15]));
  SDFFQX1 \dut_A_out_reg[0] (.CK (clk), .D (dut_A_dout[0]), .SI
       (parall_A[0]), .SE (n_64), .Q (parall_A[0]));
  SDFFQX1 \dut_A_out_reg[1] (.CK (clk), .D (dut_A_dout[1]), .SI
       (parall_A[1]), .SE (n_64), .Q (parall_A[1]));
  SDFFQX1 \dut_A_out_reg[2] (.CK (clk), .D (dut_A_dout[2]), .SI
       (parall_A[2]), .SE (n_64), .Q (parall_A[2]));
  SDFFQX1 \dut_A_out_reg[3] (.CK (clk), .D (dut_A_dout[3]), .SI
       (parall_A[3]), .SE (n_64), .Q (parall_A[3]));
  SDFFQX1 \dut_A_out_reg[4] (.CK (clk), .D (dut_A_dout[4]), .SI
       (parall_A[4]), .SE (n_64), .Q (parall_A[4]));
  SDFFQX1 \dut_A_out_reg[5] (.CK (clk), .D (dut_A_dout[5]), .SI
       (parall_A[5]), .SE (n_64), .Q (parall_A[5]));
  SDFFQX1 \dut_A_out_reg[6] (.CK (clk), .D (dut_A_dout[6]), .SI
       (parall_A[6]), .SE (n_64), .Q (parall_A[6]));
  SDFFQX1 \dut_A_out_reg[7] (.CK (clk), .D (dut_A_dout[7]), .SI
       (parall_A[7]), .SE (n_64), .Q (parall_A[7]));
  SDFFQX1 \dut_A_out_reg[8] (.CK (clk), .D (dut_A_dout[8]), .SI
       (parall_A[8]), .SE (n_64), .Q (parall_A[8]));
  SDFFQX1 \dut_A_out_reg[9] (.CK (clk), .D (dut_A_dout[9]), .SI
       (parall_A[9]), .SE (n_64), .Q (parall_A[9]));
  SDFFQX1 \dut_A_out_reg[10] (.CK (clk), .D (dut_A_dout[10]), .SI
       (parall_A[10]), .SE (n_64), .Q (parall_A[10]));
  SDFFQX1 \dut_A_out_reg[11] (.CK (clk), .D (dut_A_dout[11]), .SI
       (parall_A[11]), .SE (n_64), .Q (parall_A[11]));
  SDFFQX1 \dut_A_out_reg[12] (.CK (clk), .D (dut_A_dout[12]), .SI
       (parall_A[12]), .SE (n_64), .Q (parall_A[12]));
  SDFFQX1 \dut_A_out_reg[13] (.CK (clk), .D (dut_A_dout[13]), .SI
       (parall_A[13]), .SE (n_64), .Q (parall_A[13]));
  SDFFQX1 \dut_A_out_reg[14] (.CK (clk), .D (dut_A_dout[14]), .SI
       (parall_A[14]), .SE (n_64), .Q (parall_A[14]));
  SDFFQX1 \dut_A_out_reg[15] (.CK (clk), .D (dut_A_dout[15]), .SI
       (parall_A[15]), .SE (n_64), .Q (parall_A[15]));
  DFFRHQX1 \dut_B_cnt_reg[0] (.RN (res), .CK (clk), .D (n_27), .Q
       (dut_B_cnt[0]));
  DFFRHQX1 \dut_B_cnt_reg[1] (.RN (res), .CK (clk), .D (n_77), .Q
       (dut_B_cnt[1]));
  DFFRHQX1 \dut_B_cnt_reg[2] (.RN (res), .CK (clk), .D (n_94), .Q
       (dut_B_cnt[2]));
  DFFRHQX1 \dut_B_cnt_reg[3] (.RN (res), .CK (clk), .D (n_34), .Q
       (dut_B_cnt[3]));
  DFFRHQX1 \dut_B_cnt_reg[4] (.RN (res), .CK (clk), .D (n_89), .Q
       (dut_B_cnt[4]));
  SDFFRHQX1 \dut_B_dout_reg[0] (.RN (res), .CK (clk), .D
       (dut_B_dout[0]), .SI (B), .SE (tvalid), .Q (dut_B_dout[0]));
  SDFFRHQX1 \dut_B_dout_reg[1] (.RN (res), .CK (clk), .D
       (dut_B_dout[1]), .SI (dut_B_dout[0]), .SE (tvalid), .Q
       (dut_B_dout[1]));
  SDFFRHQX1 \dut_B_dout_reg[2] (.RN (res), .CK (clk), .D
       (dut_B_dout[2]), .SI (dut_B_dout[1]), .SE (tvalid), .Q
       (dut_B_dout[2]));
  SDFFRHQX1 \dut_B_dout_reg[3] (.RN (res), .CK (clk), .D
       (dut_B_dout[3]), .SI (dut_B_dout[2]), .SE (tvalid), .Q
       (dut_B_dout[3]));
  SDFFRHQX1 \dut_B_dout_reg[4] (.RN (res), .CK (clk), .D
       (dut_B_dout[4]), .SI (dut_B_dout[3]), .SE (tvalid), .Q
       (dut_B_dout[4]));
  SDFFRHQX1 \dut_B_dout_reg[5] (.RN (res), .CK (clk), .D
       (dut_B_dout[5]), .SI (dut_B_dout[4]), .SE (tvalid), .Q
       (dut_B_dout[5]));
  SDFFRHQX1 \dut_B_dout_reg[6] (.RN (res), .CK (clk), .D
       (dut_B_dout[6]), .SI (dut_B_dout[5]), .SE (tvalid), .Q
       (dut_B_dout[6]));
  SDFFRHQX1 \dut_B_dout_reg[7] (.RN (res), .CK (clk), .D
       (dut_B_dout[7]), .SI (dut_B_dout[6]), .SE (tvalid), .Q
       (dut_B_dout[7]));
  SDFFRHQX1 \dut_B_dout_reg[8] (.RN (res), .CK (clk), .D
       (dut_B_dout[8]), .SI (dut_B_dout[7]), .SE (tvalid), .Q
       (dut_B_dout[8]));
  SDFFRHQX1 \dut_B_dout_reg[9] (.RN (res), .CK (clk), .D
       (dut_B_dout[9]), .SI (dut_B_dout[8]), .SE (tvalid), .Q
       (dut_B_dout[9]));
  SDFFRHQX1 \dut_B_dout_reg[10] (.RN (res), .CK (clk), .D
       (dut_B_dout[10]), .SI (dut_B_dout[9]), .SE (tvalid), .Q
       (dut_B_dout[10]));
  SDFFRHQX1 \dut_B_dout_reg[11] (.RN (res), .CK (clk), .D
       (dut_B_dout[11]), .SI (dut_B_dout[10]), .SE (tvalid), .Q
       (dut_B_dout[11]));
  SDFFRHQX1 \dut_B_dout_reg[12] (.RN (res), .CK (clk), .D
       (dut_B_dout[12]), .SI (dut_B_dout[11]), .SE (tvalid), .Q
       (dut_B_dout[12]));
  SDFFRHQX1 \dut_B_dout_reg[13] (.RN (res), .CK (clk), .D
       (dut_B_dout[13]), .SI (dut_B_dout[12]), .SE (tvalid), .Q
       (dut_B_dout[13]));
  SDFFRHQX1 \dut_B_dout_reg[14] (.RN (res), .CK (clk), .D
       (dut_B_dout[14]), .SI (dut_B_dout[13]), .SE (tvalid), .Q
       (dut_B_dout[14]));
  SDFFRHQX1 \dut_B_dout_reg[15] (.RN (res), .CK (clk), .D
       (dut_B_dout[15]), .SI (dut_B_dout[14]), .SE (tvalid), .Q
       (dut_B_dout[15]));
  SDFFQX1 \dut_B_out_reg[0] (.CK (clk), .D (dut_B_dout[0]), .SI
       (parall_B[0]), .SE (n_64), .Q (parall_B[0]));
  SDFFQX1 \dut_B_out_reg[1] (.CK (clk), .D (dut_B_dout[1]), .SI
       (parall_B[1]), .SE (n_64), .Q (parall_B[1]));
  SDFFQX1 \dut_B_out_reg[2] (.CK (clk), .D (dut_B_dout[2]), .SI
       (parall_B[2]), .SE (n_64), .Q (parall_B[2]));
  SDFFQX1 \dut_B_out_reg[3] (.CK (clk), .D (dut_B_dout[3]), .SI
       (parall_B[3]), .SE (n_64), .Q (parall_B[3]));
  SDFFQX1 \dut_B_out_reg[4] (.CK (clk), .D (dut_B_dout[4]), .SI
       (parall_B[4]), .SE (n_64), .Q (parall_B[4]));
  SDFFQX1 \dut_B_out_reg[5] (.CK (clk), .D (dut_B_dout[5]), .SI
       (parall_B[5]), .SE (n_64), .Q (parall_B[5]));
  SDFFQX1 \dut_B_out_reg[6] (.CK (clk), .D (dut_B_dout[6]), .SI
       (parall_B[6]), .SE (n_64), .Q (parall_B[6]));
  SDFFQX1 \dut_B_out_reg[7] (.CK (clk), .D (dut_B_dout[7]), .SI
       (parall_B[7]), .SE (n_64), .Q (parall_B[7]));
  SDFFQX1 \dut_B_out_reg[8] (.CK (clk), .D (dut_B_dout[8]), .SI
       (parall_B[8]), .SE (n_64), .Q (parall_B[8]));
  SDFFQX1 \dut_B_out_reg[9] (.CK (clk), .D (dut_B_dout[9]), .SI
       (parall_B[9]), .SE (n_64), .Q (parall_B[9]));
  SDFFQX1 \dut_B_out_reg[10] (.CK (clk), .D (dut_B_dout[10]), .SI
       (parall_B[10]), .SE (n_64), .Q (parall_B[10]));
  SDFFQX1 \dut_B_out_reg[11] (.CK (clk), .D (dut_B_dout[11]), .SI
       (parall_B[11]), .SE (n_64), .Q (parall_B[11]));
  SDFFQX1 \dut_B_out_reg[12] (.CK (clk), .D (dut_B_dout[12]), .SI
       (parall_B[12]), .SE (n_64), .Q (parall_B[12]));
  SDFFQX1 \dut_B_out_reg[13] (.CK (clk), .D (dut_B_dout[13]), .SI
       (parall_B[13]), .SE (n_64), .Q (parall_B[13]));
  SDFFQX1 \dut_B_out_reg[14] (.CK (clk), .D (dut_B_dout[14]), .SI
       (parall_B[14]), .SE (n_64), .Q (parall_B[14]));
  SDFFQX1 \dut_B_out_reg[15] (.CK (clk), .D (dut_B_dout[15]), .SI
       (parall_B[15]), .SE (n_64), .Q (parall_B[15]));
  DFFRHQX1 \dut_div_fraction_cnt_reg[0] (.RN (res), .CK (clk), .D
       (n_71), .Q (dut_div_fraction_cnt[0]));
  DFFRHQX1 \dut_div_fraction_cnt_reg[1] (.RN (res), .CK (clk), .D
       (n_65), .Q (dut_div_fraction_cnt[1]));
  DFFRHQX1 \dut_div_fraction_cnt_reg[2] (.RN (res), .CK (clk), .D
       (n_98), .Q (dut_div_fraction_cnt[2]));
  DFFRHQX1 \dut_div_fraction_cnt_reg[3] (.RN (res), .CK (clk), .D
       (n_135), .Q (dut_div_fraction_cnt[3]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[0] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[0]), .SI (fraction[0]), .SE
       (n_51), .Q (fraction[0]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[1] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[1]), .SI (fraction[1]), .SE
       (n_51), .Q (fraction[1]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[2] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[2]), .SI (fraction[2]), .SE
       (n_51), .Q (fraction[2]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[3] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[3]), .SI (fraction[3]), .SE
       (n_51), .Q (fraction[3]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[4] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[4]), .SI (fraction[4]), .SE
       (n_51), .Q (fraction[4]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[5] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[5]), .SI (fraction[5]), .SE
       (n_51), .Q (fraction[5]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[6] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[6]), .SI (fraction[6]), .SE
       (n_51), .Q (fraction[6]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[7] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[7]), .SI (fraction[7]), .SE
       (n_51), .Q (fraction[7]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[8] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[8]), .SI (fraction[8]), .SE
       (n_51), .Q (fraction[8]));
  SDFFRHQX1 \dut_div_fraction_fraction_reg[9] (.RN (res), .CK (clk), .D
       (dut_div_fraction_reg_quotient[9]), .SI (fraction[9]), .SE
       (n_51), .Q (fraction[9]));
  DFFRHQX1 dut_div_fraction_load_reg(.RN (res), .CK (clk), .D (n_46),
       .Q (load1));
  DFFRHQX1 dut_div_fraction_ready_stop_reg(.RN (res), .CK (clk), .D
       (n_45), .Q (ready_stop1));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[1] (.RN (res), .CK (clk),
       .D (n_63), .Q (dut_div_fraction_reg_quotient[1]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[2] (.RN (res), .CK (clk),
       .D (n_62), .Q (dut_div_fraction_reg_quotient[2]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[3] (.RN (res), .CK (clk),
       .D (n_70), .Q (dut_div_fraction_reg_quotient[3]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[4] (.RN (res), .CK (clk),
       .D (n_69), .Q (dut_div_fraction_reg_quotient[4]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[5] (.RN (res), .CK (clk),
       .D (n_68), .Q (dut_div_fraction_reg_quotient[5]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[6] (.RN (res), .CK (clk),
       .D (n_67), .Q (dut_div_fraction_reg_quotient[6]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[7] (.RN (res), .CK (clk),
       .D (n_66), .Q (dut_div_fraction_reg_quotient[7]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[8] (.RN (res), .CK (clk),
       .D (n_73), .Q (dut_div_fraction_reg_quotient[8]));
  DFFRHQX1 \dut_div_fraction_reg_quotient_reg[9] (.RN (res), .CK (clk),
       .D (n_72), .Q (dut_div_fraction_reg_quotient[9]));
  DFFRHQX1 \dut_div_fraction_remains_reg[1] (.RN (res), .CK (clk), .D
       (n_59), .Q (dut_div_fraction_remains[1]));
  DFFRHQX1 \dut_div_fraction_remains_reg[2] (.RN (res), .CK (clk), .D
       (n_87), .Q (dut_div_fraction_remains[2]));
  DFFRHQX1 \dut_div_fraction_remains_reg[3] (.RN (res), .CK (clk), .D
       (n_86), .Q (dut_div_fraction_remains[3]));
  DFFRHQX1 \dut_div_fraction_remains_reg[4] (.RN (res), .CK (clk), .D
       (n_85), .Q (dut_div_fraction_remains[4]));
  DFFRHQX1 \dut_div_fraction_remains_reg[5] (.RN (res), .CK (clk), .D
       (n_83), .Q (dut_div_fraction_remains[5]));
  DFFRHQX1 \dut_div_fraction_remains_reg[6] (.RN (res), .CK (clk), .D
       (n_90), .Q (dut_div_fraction_remains[6]));
  DFFRHQX1 \dut_div_fraction_remains_reg[7] (.RN (res), .CK (clk), .D
       (n_82), .Q (dut_div_fraction_remains[7]));
  DFFRHQX1 \dut_div_fraction_remains_reg[8] (.RN (res), .CK (clk), .D
       (n_84), .Q (dut_div_fraction_remains[8]));
  DFFRHQX1 \dut_div_fraction_remains_reg[9] (.RN (res), .CK (clk), .D
       (n_88), .Q (dut_div_fraction_remains[9]));
  DFFRHQX1 \dut_out_cnt_reg[0] (.RN (res), .CK (clk), .D (n_101), .Q
       (dut_out_cnt[0]));
  DFFRHQX1 \dut_out_cnt_reg[1] (.RN (res), .CK (clk), .D (n_100), .Q
       (dut_out_cnt[1]));
  DFFRHQX1 \dut_out_cnt_reg[2] (.RN (res), .CK (clk), .D (n_102), .Q
       (dut_out_cnt[2]));
  DFFRHQX1 \dut_out_cnt_reg[3] (.RN (res), .CK (clk), .D (n_97), .Q
       (dut_out_cnt[3]));
  DFFRHQX1 \dut_out_dout_reg[0] (.RN (res), .CK (clk), .D (n_133), .Q
       (dut_out_dout[0]));
  DFFRHQX1 \dut_out_dout_reg[1] (.RN (res), .CK (clk), .D (n_137), .Q
       (dut_out_dout[1]));
  DFFRHQX1 \dut_out_dout_reg[2] (.RN (res), .CK (clk), .D (n_134), .Q
       (dut_out_dout[2]));
  DFFRHQX1 \dut_out_dout_reg[3] (.RN (res), .CK (clk), .D (n_136), .Q
       (dut_out_dout[3]));
  DFFRHQX1 \dut_out_dout_reg[4] (.RN (res), .CK (clk), .D (n_138), .Q
       (dut_out_dout[4]));
  DFFRHQX1 \dut_out_dout_reg[5] (.RN (res), .CK (clk), .D (n_131), .Q
       (dut_out_dout[5]));
  DFFRHQX1 \dut_out_dout_reg[6] (.RN (res), .CK (clk), .D (n_132), .Q
       (dut_out_dout[6]));
  DFFRHQX1 \dut_out_dout_reg[7] (.RN (res), .CK (clk), .D (n_130), .Q
       (dut_out_dout[7]));
  DFFRHQX1 \dut_out_dout_reg[8] (.RN (res), .CK (clk), .D (n_129), .Q
       (dut_out_dout[8]));
  DFFRHQX1 \dut_out_dout_reg[9] (.RN (res), .CK (clk), .D (n_128), .Q
       (dut_out_dout[9]));
  DFFRHQX1 \dut_out_dout_reg[10] (.RN (res), .CK (clk), .D (n_127), .Q
       (dut_out_dout[10]));
  DFFRHQX1 \dut_out_dout_reg[11] (.RN (res), .CK (clk), .D (n_126), .Q
       (dut_out_dout[11]));
  DFFRHQX1 \dut_out_dout_reg[12] (.RN (res), .CK (clk), .D (n_125), .Q
       (dut_out_dout[12]));
  DFFRHQX1 \dut_out_dout_reg[13] (.RN (res), .CK (clk), .D (n_124), .Q
       (dut_out_dout[13]));
  DFFRHQX1 \dut_out_dout_reg[14] (.RN (res), .CK (clk), .D (n_123), .Q
       (dut_out_dout[14]));
  DFFRHQX1 \dut_out_dout_reg[15] (.RN (res), .CK (clk), .D (n_107), .Q
       (dut_out_dout[15]));
  SDFFRHQX1 dut_out_load_done_reg(.RN (res), .CK (clk), .D (load_done),
       .SI (n_30), .SE (n_96), .Q (load_done));
  DFFRHQX1 dut_out_out_reg(.RN (res), .CK (clk), .D (n_106), .Q (out));
  DFFRHQX1 dut_out_tready_reg(.RN (res), .CK (clk), .D (n_99), .Q
       (tready));
  SDFFRHQX1 \dut_summator_exponent_reg[0] (.RN (res), .CK (clk), .D
       (n_23), .SI (exponent[0]), .SE (n_10), .Q (exponent[0]));
  SDFFRHQX1 \dut_summator_exponent_reg[1] (.RN (res), .CK (clk), .D
       (n_80), .SI (exponent[1]), .SE (n_10), .Q (exponent[1]));
  SDFFRHQX1 \dut_summator_exponent_reg[2] (.RN (res), .CK (clk), .D
       (n_104), .SI (exponent[2]), .SE (n_10), .Q (exponent[2]));
  SDFFRHQX1 \dut_summator_exponent_reg[3] (.RN (res), .CK (clk), .D
       (n_140), .SI (exponent[3]), .SE (n_10), .Q (exponent[3]));
  SDFFRHQX1 \dut_summator_exponent_reg[4] (.RN (res), .CK (clk), .D
       (n_141), .SI (exponent[4]), .SE (n_10), .Q (exponent[4]));
  DFFRHQX1 dut_summator_load_reg(.RN (res), .CK (clk), .D (n_9), .Q
       (load));
  DFFRHQX1 dut_summator_ready_stop_reg(.RN (res), .CK (clk), .D (n_15),
       .Q (ready_stop));
  SDFFRHQX1 dut_summator_sign_reg(.RN (res), .CK (clk), .D (n_12), .SI
       (sign), .SE (n_10), .Q (sign));
  XNOR2X1 g2858(.A (n_11), .B (n_139), .Y (n_141));
  ADDFX1 g2859(.A (divisible[13]), .B (n_5), .CI (n_103), .CO (n_139),
       .S (n_140));
  OAI2BB1X1 g2877(.A0N (dut_out_dout[4]), .A1N (n_1), .B0 (n_120), .Y
       (n_138));
  OAI2BB1X1 g2878(.A0N (dut_out_dout[1]), .A1N (n_1), .B0 (n_117), .Y
       (n_137));
  OAI2BB1X1 g2879(.A0N (dut_out_dout[3]), .A1N (n_1), .B0 (n_119), .Y
       (n_136));
  NOR2XL g2880(.A (n_7), .B (n_105), .Y (n_135));
  OAI2BB1X1 g2881(.A0N (dut_out_dout[2]), .A1N (n_1), .B0 (n_118), .Y
       (n_134));
  OAI2BB1X1 g2882(.A0N (dut_out_dout[1]), .A1N (n_95), .B0 (n_122), .Y
       (n_133));
  OAI2BB1X1 g2886(.A0N (dut_out_dout[7]), .A1N (n_95), .B0 (n_110), .Y
       (n_132));
  OAI2BB1X1 g2887(.A0N (dut_out_dout[6]), .A1N (n_95), .B0 (n_121), .Y
       (n_131));
  OAI2BB1X1 g2888(.A0N (dut_out_dout[7]), .A1N (n_1), .B0 (n_115), .Y
       (n_130));
  OAI2BB1X1 g2889(.A0N (dut_out_dout[9]), .A1N (n_95), .B0 (n_114), .Y
       (n_129));
  OAI2BB1X1 g2890(.A0N (dut_out_dout[10]), .A1N (n_95), .B0 (n_112), .Y
       (n_128));
  OAI2BB1X1 g2891(.A0N (dut_out_dout[10]), .A1N (n_1), .B0 (n_113), .Y
       (n_127));
  OAI2BB1X1 g2892(.A0N (dut_out_dout[11]), .A1N (n_1), .B0 (n_111), .Y
       (n_126));
  OAI2BB1X1 g2893(.A0N (dut_out_dout[12]), .A1N (n_1), .B0 (n_116), .Y
       (n_125));
  OAI2BB1X1 g2894(.A0N (dut_out_dout[13]), .A1N (n_1), .B0 (n_109), .Y
       (n_124));
  OAI2BB1X1 g2895(.A0N (dut_out_dout[15]), .A1N (n_95), .B0 (n_108), .Y
       (n_123));
  AOI22XL g2896(.A0 (dut_out_dout[0]), .A1 (n_1), .B0 (fraction[0]),
       .B1 (n_30), .Y (n_122));
  AOI22XL g2897(.A0 (dut_out_dout[5]), .A1 (n_1), .B0 (fraction[5]),
       .B1 (n_30), .Y (n_121));
  AOI22XL g2898(.A0 (dut_out_dout[5]), .A1 (n_95), .B0 (fraction[4]),
       .B1 (n_30), .Y (n_120));
  AOI22XL g2899(.A0 (dut_out_dout[4]), .A1 (n_95), .B0 (fraction[3]),
       .B1 (n_30), .Y (n_119));
  AOI22XL g2900(.A0 (dut_out_dout[3]), .A1 (n_95), .B0 (fraction[2]),
       .B1 (n_30), .Y (n_118));
  AOI22XL g2901(.A0 (dut_out_dout[2]), .A1 (n_95), .B0 (fraction[1]),
       .B1 (n_30), .Y (n_117));
  AOI22XL g2908(.A0 (dut_out_dout[13]), .A1 (n_95), .B0 (exponent[2]),
       .B1 (n_30), .Y (n_116));
  AOI22XL g2909(.A0 (dut_out_dout[8]), .A1 (n_95), .B0 (fraction[7]),
       .B1 (n_30), .Y (n_115));
  AOI22XL g2910(.A0 (dut_out_dout[8]), .A1 (n_1), .B0 (fraction[8]),
       .B1 (n_30), .Y (n_114));
  AOI22XL g2911(.A0 (dut_out_dout[11]), .A1 (n_95), .B0 (exponent[0]),
       .B1 (n_30), .Y (n_113));
  AOI22XL g2912(.A0 (dut_out_dout[9]), .A1 (n_1), .B0 (fraction[9]),
       .B1 (n_30), .Y (n_112));
  AOI22XL g2913(.A0 (dut_out_dout[12]), .A1 (n_95), .B0 (exponent[1]),
       .B1 (n_30), .Y (n_111));
  AOI22XL g2914(.A0 (dut_out_dout[6]), .A1 (n_1), .B0 (fraction[6]),
       .B1 (n_30), .Y (n_110));
  AOI22XL g2915(.A0 (dut_out_dout[14]), .A1 (n_95), .B0 (exponent[3]),
       .B1 (n_30), .Y (n_109));
  AOI22XL g2916(.A0 (dut_out_dout[14]), .A1 (n_1), .B0 (exponent[4]),
       .B1 (n_30), .Y (n_108));
  AO22X1 g2917(.A0 (dut_out_dout[15]), .A1 (n_1), .B0 (sign), .B1
       (n_30), .Y (n_107));
  AO22X1 g2918(.A0 (dut_out_dout[0]), .A1 (n_95), .B0 (out), .B1
       (n_30), .Y (n_106));
  MXI2XL g2919(.A (n_93), .B (dut_div_fraction_cnt[3]), .S0 (n_18), .Y
       (n_105));
  ADDFX1 g2920(.A (divisible[12]), .B (n_4), .CI (n_79), .CO (n_103),
       .S (n_104));
  AND2X1 g2941(.A (n_95), .B (n_78), .Y (n_102));
  NOR2XL g2942(.A (dut_out_cnt[0]), .B (n_96), .Y (n_101));
  AND2X1 g2943(.A (n_95), .B (n_29), .Y (n_100));
  OR2X1 g2944(.A (tready), .B (n_95), .Y (n_99));
  NOR2XL g2945(.A (n_7), .B (n_92), .Y (n_98));
  OA21X1 g2946(.A0 (dut_out_cnt[3]), .A1 (n_81), .B0 (n_95), .Y (n_97));
  CLKINVX4 g2973(.A (n_96), .Y (n_95));
  CLKXOR2X1 g2974(.A (dut_B_cnt[2]), .B (n_76), .Y (n_94));
  CLKXOR2X1 g2975(.A (dut_div_fraction_cnt[3]), .B (n_74), .Y (n_93));
  MXI2XL g2976(.A (n_75), .B (dut_div_fraction_cnt[2]), .S0 (n_18), .Y
       (n_92));
  NAND2XL g2985(.A (n_31), .B (n_91), .Y (n_96));
  OAI2BB1X1 g2999(.A0N (dut_div_fraction_remains[5]), .A1N (n_17), .B0
       (n_54), .Y (n_90));
  OAI2BB1X1 g3000(.A0N (dut_B_cnt[4]), .A1N (n_44), .B0 (n_47), .Y
       (n_89));
  OAI2BB1X1 g3001(.A0N (dut_div_fraction_remains[8]), .A1N (n_17), .B0
       (n_61), .Y (n_88));
  OAI2BB1X1 g3002(.A0N (dut_div_fraction_remains[1]), .A1N (n_17), .B0
       (n_58), .Y (n_87));
  OAI2BB1X1 g3003(.A0N (dut_div_fraction_remains[2]), .A1N (n_17), .B0
       (n_57), .Y (n_86));
  OAI2BB1X1 g3004(.A0N (dut_div_fraction_remains[3]), .A1N (n_17), .B0
       (n_56), .Y (n_85));
  OAI2BB1X1 g3005(.A0N (dut_div_fraction_remains[7]), .A1N (n_17), .B0
       (n_52), .Y (n_84));
  OAI2BB1X1 g3006(.A0N (dut_div_fraction_remains[4]), .A1N (n_17), .B0
       (n_55), .Y (n_83));
  OAI2BB1X1 g3007(.A0N (dut_div_fraction_remains[6]), .A1N (n_17), .B0
       (n_53), .Y (n_82));
  NAND2XL g3008(.A (dut_out_cnt[3]), .B (n_81), .Y (n_91));
  ADDFX1 g3011(.A (divisible[11]), .B (n_3), .CI (n_22), .CO (n_79), .S
       (n_80));
  ADDHX1 g3012(.A (dut_out_cnt[2]), .B (n_28), .CO (n_81), .S (n_78));
  ADDHX1 g3013(.A (dut_B_cnt[1]), .B (n_26), .CO (n_76), .S (n_77));
  ADDHX1 g3014(.A (dut_div_fraction_cnt[2]), .B (n_24), .CO (n_74), .S
       (n_75));
  NOR2XL g3015(.A (n_7), .B (n_40), .Y (n_73));
  NOR2XL g3016(.A (n_7), .B (n_39), .Y (n_72));
  NOR2XL g3017(.A (n_7), .B (n_35), .Y (n_71));
  NOR2XL g3018(.A (n_7), .B (n_49), .Y (n_70));
  NOR2XL g3019(.A (n_7), .B (n_50), .Y (n_69));
  NOR2XL g3020(.A (n_7), .B (n_43), .Y (n_68));
  NOR2XL g3021(.A (n_7), .B (n_42), .Y (n_67));
  NOR2XL g3022(.A (n_7), .B (n_41), .Y (n_66));
  NOR2XL g3023(.A (n_7), .B (n_38), .Y (n_65));
  NOR2XL g3028(.A (n_7), .B (n_37), .Y (n_63));
  NOR2XL g3029(.A (n_7), .B (n_36), .Y (n_62));
  AOI22XL g3030(.A0 (dut_div_fraction_remains[9]), .A1 (n_33), .B0
       (divisible[8]), .B1 (n_7), .Y (n_61));
  OAI22XL g3031(.A0 (n_2), .A1 (n_32), .B0
       (dut_div_fraction_remains[9]), .B1 (n_18), .Y (n_60));
  AO22X1 g3032(.A0 (dut_div_fraction_remains[1]), .A1 (n_33), .B0
       (divisible[0]), .B1 (n_7), .Y (n_59));
  AOI22XL g3033(.A0 (dut_div_fraction_remains[2]), .A1 (n_33), .B0
       (divisible[1]), .B1 (n_7), .Y (n_58));
  AOI22XL g3034(.A0 (dut_div_fraction_remains[3]), .A1 (n_33), .B0
       (divisible[2]), .B1 (n_7), .Y (n_57));
  AOI22XL g3035(.A0 (dut_div_fraction_remains[4]), .A1 (n_33), .B0
       (divisible[3]), .B1 (n_7), .Y (n_56));
  AOI22XL g3036(.A0 (dut_div_fraction_remains[5]), .A1 (n_33), .B0
       (divisible[4]), .B1 (n_7), .Y (n_55));
  AOI22XL g3037(.A0 (dut_div_fraction_remains[6]), .A1 (n_33), .B0
       (divisible[5]), .B1 (n_7), .Y (n_54));
  AOI22XL g3038(.A0 (dut_div_fraction_remains[7]), .A1 (n_33), .B0
       (divisible[6]), .B1 (n_7), .Y (n_53));
  AOI22XL g3039(.A0 (dut_div_fraction_remains[8]), .A1 (n_33), .B0
       (divisible[7]), .B1 (n_7), .Y (n_52));
  OR2X2 g3040(.A (tvalid), .B (n_48), .Y (n_64));
  MXI2XL g3041(.A (dut_div_fraction_reg_quotient[4]), .B
       (dut_div_fraction_reg_quotient[3]), .S0 (n_17), .Y (n_50));
  MXI2XL g3042(.A (dut_div_fraction_reg_quotient[3]), .B
       (dut_div_fraction_reg_quotient[2]), .S0 (n_17), .Y (n_49));
  NAND3XL g3043(.A (res), .B (dut_B_cnt[4]), .C (n_21), .Y (n_48));
  NAND3BXL g3044(.AN (dut_B_cnt[4]), .B (dut_B_cnt[3]), .C (n_0), .Y
       (n_47));
  OA21X1 g3045(.A0 (load1), .A1 (n_20), .B0 (n_33), .Y (n_46));
  OAI2BB1X1 g3046(.A0N (ready_stop1), .A1N (n_19), .B0 (n_8), .Y
       (n_45));
  MXI2XL g3047(.A (n_21), .B (n_16), .S0 (tvalid), .Y (n_44));
  NAND2X2 g3049(.A (n_20), .B (n_33), .Y (n_51));
  MXI2XL g3050(.A (dut_div_fraction_reg_quotient[5]), .B
       (dut_div_fraction_reg_quotient[4]), .S0 (n_17), .Y (n_43));
  MXI2XL g3051(.A (dut_div_fraction_reg_quotient[6]), .B
       (dut_div_fraction_reg_quotient[5]), .S0 (n_17), .Y (n_42));
  MXI2XL g3052(.A (dut_div_fraction_reg_quotient[7]), .B
       (dut_div_fraction_reg_quotient[6]), .S0 (n_17), .Y (n_41));
  MXI2XL g3053(.A (dut_div_fraction_reg_quotient[8]), .B
       (dut_div_fraction_reg_quotient[7]), .S0 (n_17), .Y (n_40));
  MXI2XL g3054(.A (dut_div_fraction_reg_quotient[9]), .B
       (dut_div_fraction_reg_quotient[8]), .S0 (n_17), .Y (n_39));
  MXI2XL g3055(.A (dut_div_fraction_cnt[1]), .B (n_25), .S0 (n_17), .Y
       (n_38));
  MXI2XL g3056(.A (dut_div_fraction_reg_quotient[1]), .B
       (dut_div_fraction_reg_quotient[0]), .S0 (n_17), .Y (n_37));
  MXI2XL g3057(.A (dut_div_fraction_reg_quotient[2]), .B
       (dut_div_fraction_reg_quotient[1]), .S0 (n_17), .Y (n_36));
  XNOR2X1 g3058(.A (dut_div_fraction_cnt[0]), .B (n_17), .Y (n_35));
  CLKXOR2X1 g3059(.A (dut_B_cnt[3]), .B (n_0), .Y (n_34));
  CLKINVX4 g3061(.A (n_32), .Y (n_33));
  INVX2 g3062(.A (n_31), .Y (n_30));
  NAND2XL g3063(.A (n_8), .B (n_18), .Y (n_32));
  NAND3BX1 g3064(.AN (load_done), .B (load), .C (load1), .Y (n_31));
  ADDHX1 g3065(.A (dut_out_cnt[1]), .B (dut_out_cnt[0]), .CO (n_28), .S
       (n_29));
  ADDHX1 g3066(.A (tvalid), .B (dut_B_cnt[0]), .CO (n_26), .S (n_27));
  ADDHX1 g3067(.A (dut_div_fraction_cnt[1]), .B
       (dut_div_fraction_cnt[0]), .CO (n_24), .S (n_25));
  ADDHX1 g3068(.A (divisible[10]), .B (n_6), .CO (n_22), .S (n_23));
  INVX1 g3088(.A (n_20), .Y (n_19));
  CLKINVX4 g3089(.A (n_18), .Y (n_17));
  NOR2BX1 g3090(.AN (dut_B_cnt[3]), .B (n_13), .Y (n_16));
  NOR4X1 g3091(.A (dut_B_cnt[0]), .B (dut_B_cnt[1]), .C (dut_B_cnt[3]),
       .D (dut_B_cnt[2]), .Y (n_21));
  NOR4BBX1 g3107(.AN (dut_div_fraction_cnt[3]), .BN
       (dut_div_fraction_cnt[1]), .C (dut_div_fraction_cnt[2]), .D
       (dut_div_fraction_cnt[0]), .Y (n_20));
  NAND2X1 g3108(.A (ready_stop1), .B (n_14), .Y (n_18));
  OR2X1 g3110(.A (ready_stop), .B (n_10), .Y (n_15));
  OAI21XL g3111(.A0 (dut_div_fraction_cnt[1]), .A1
       (dut_div_fraction_cnt[2]), .B0 (dut_div_fraction_cnt[3]), .Y
       (n_14));
  CLKXOR2X1 g3112(.A (divider[15]), .B (divisible[15]), .Y (n_12));
  XNOR2X1 g3113(.A (divisible[14]), .B (divider[14]), .Y (n_11));
  NAND3XL g3114(.A (dut_B_cnt[2]), .B (dut_B_cnt[1]), .C
       (dut_B_cnt[0]), .Y (n_13));
  INVX1 g3115(.A (n_9), .Y (n_10));
  NAND2BXL g3116(.AN (ready_stop), .B (ready), .Y (n_9));
  CLKINVX4 g3117(.A (n_8), .Y (n_7));
  NAND2BX1 g3118(.AN (ready_stop1), .B (ready), .Y (n_8));
  INVX2 g3119(.A (divider[10]), .Y (n_6));
  INVX2 g3120(.A (divider[13]), .Y (n_5));
  INVX2 g3121(.A (divider[12]), .Y (n_4));
  INVX2 g3122(.A (divider[11]), .Y (n_3));
  DFFRX1 \dut_div_fraction_reg_quotient_reg[0] (.RN (res), .CK (clk),
       .D (n_60), .Q (dut_div_fraction_reg_quotient[0]), .QN (n_2));
  NOR2BX2 g2(.AN (n_31), .B (n_91), .Y (n_1));
  NOR2BX1 g3127(.AN (tvalid), .B (n_13), .Y (n_0));
  DFFRHQX1 \dut_comparator_divider_reg[10] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1971), .Q (divider[10]));
  DFFRHQX1 \dut_comparator_divider_reg[11] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1943), .Q (divider[11]));
  DFFRHQX1 \dut_comparator_divider_reg[12] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1946), .Q (divider[12]));
  DFFRHQX1 \dut_comparator_divider_reg[13] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1947), .Q (divider[13]));
  DFFRHQX1 \dut_comparator_divider_reg[14] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1948), .Q (divider[14]));
  DFFRHQX1 \dut_comparator_divider_reg[15] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1942), .Q (divider[15]));
  DFFRHQX1 \dut_comparator_divisible_reg[0] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1949), .Q (divisible[0]));
  DFFRHQX1 \dut_comparator_divisible_reg[1] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1950), .Q (divisible[1]));
  DFFRHQX1 \dut_comparator_divisible_reg[2] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1951), .Q (divisible[2]));
  DFFRHQX1 \dut_comparator_divisible_reg[3] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1952), .Q (divisible[3]));
  DFFRHQX1 \dut_comparator_divisible_reg[4] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1953), .Q (divisible[4]));
  DFFRHQX1 \dut_comparator_divisible_reg[5] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1961), .Q (divisible[5]));
  DFFRHQX1 \dut_comparator_divisible_reg[6] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1957), .Q (divisible[6]));
  DFFRHQX1 \dut_comparator_divisible_reg[7] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1958), .Q (divisible[7]));
  DFFRHQX1 \dut_comparator_divisible_reg[8] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1959), .Q (divisible[8]));
  DFFRHQX1 \dut_comparator_divisible_reg[10] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1960), .Q (divisible[10]));
  DFFRHQX1 \dut_comparator_divisible_reg[11] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1954), .Q (divisible[11]));
  DFFRHQX1 \dut_comparator_divisible_reg[12] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1962), .Q (divisible[12]));
  DFFRHQX1 \dut_comparator_divisible_reg[13] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1965), .Q (divisible[13]));
  DFFRHQX1 \dut_comparator_divisible_reg[14] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1968), .Q (divisible[14]));
  DFFRHQX1 \dut_comparator_divisible_reg[15] (.RN (res), .CK (clk), .D
       (dut_comparator_n_1974), .Q (divisible[15]));
  DFFRHQX1 dut_comparator_ready_reg(.RN (res), .CK (clk), .D
       (dut_comparator_n_1977), .Q (ready));
  AO22X1 dut_comparator_g3086(.A0 (parall_A[15]), .A1
       (dut_comparator_n_1990), .B0 (parall_B[15]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1942));
  AO22X1 dut_comparator_g3087(.A0 (parall_A[11]), .A1
       (dut_comparator_n_1990), .B0 (parall_B[11]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1943));
  AO22X1 dut_comparator_g3088(.A0 (parall_A[12]), .A1
       (dut_comparator_n_1990), .B0 (parall_B[12]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1946));
  AO22X1 dut_comparator_g3089(.A0 (parall_A[13]), .A1
       (dut_comparator_n_1990), .B0 (parall_B[13]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1947));
  AO22X1 dut_comparator_g3090(.A0 (parall_A[14]), .A1
       (dut_comparator_n_1990), .B0 (parall_B[14]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1948));
  AO22X1 dut_comparator_g3092(.A0 (parall_B[0]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[0]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1949));
  AO22X1 dut_comparator_g3093(.A0 (parall_B[1]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[1]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1950));
  AO22X1 dut_comparator_g3094(.A0 (parall_B[2]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[2]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1951));
  AO22X1 dut_comparator_g3095(.A0 (parall_B[3]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[3]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1952));
  AO22X1 dut_comparator_g3096(.A0 (parall_B[4]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[4]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1953));
  AO22X1 dut_comparator_g3097(.A0 (parall_B[11]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[11]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1954));
  AO22X1 dut_comparator_g3098(.A0 (parall_B[6]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[6]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1957));
  AO22X1 dut_comparator_g3099(.A0 (parall_B[7]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[7]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1958));
  AO22X1 dut_comparator_g3100(.A0 (parall_B[8]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[8]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1959));
  AO22X1 dut_comparator_g3101(.A0 (parall_B[10]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[10]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1960));
  AO22X1 dut_comparator_g3102(.A0 (parall_B[5]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[5]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1961));
  AO22X1 dut_comparator_g3103(.A0 (parall_B[12]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[12]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1962));
  AO22X1 dut_comparator_g3104(.A0 (parall_B[13]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[13]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1965));
  AO22X1 dut_comparator_g3105(.A0 (parall_B[14]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[14]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1968));
  AO22X1 dut_comparator_g3106(.A0 (parall_A[10]), .A1
       (dut_comparator_n_1990), .B0 (parall_B[10]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1971));
  AO22X1 dut_comparator_g3107(.A0 (parall_B[15]), .A1
       (dut_comparator_n_1990), .B0 (parall_A[15]), .B1
       (dut_comparator_n_1978), .Y (dut_comparator_n_1974));
  OR2X1 dut_comparator_g3108(.A (dut_comparator_n_1990), .B
       (dut_comparator_n_1978), .Y (dut_comparator_n_1977));
  AND2X2 dut_comparator_g3109(.A (dut_comparator_n_2092), .B
       (dut_comparator_n_1989), .Y (dut_comparator_n_1978));
  AOI221X1 dut_comparator_g3110(.A0 (dut_comparator_n_2091), .A1
       (dut_comparator_n_2031), .B0 (dut_comparator_n_2181), .B1
       (dut_comparator_n_2062), .C0 (dut_comparator_n_2001), .Y
       (dut_comparator_n_1989));
  AND2X2 dut_comparator_g3111(.A (dut_comparator_n_2090), .B
       (dut_comparator_n_2003), .Y (dut_comparator_n_1990));
  OAI2BB1X1 dut_comparator_g3112(.A0N (dut_comparator_n_2084), .A1N
       (dut_comparator_n_2090), .B0 (dut_comparator_n_2004), .Y
       (dut_comparator_n_2001));
  AOI221X1 dut_comparator_g3113(.A0 (dut_comparator_n_2051), .A1
       (dut_comparator_n_2016), .B0 (dut_comparator_n_2053), .B1
       (dut_comparator_n_2024), .C0 (dut_comparator_n_2006), .Y
       (dut_comparator_n_2003));
  OAI211X1 dut_comparator_g3114(.A0 (dut_comparator_n_2109), .A1
       (dut_comparator_n_2007), .B0 (dut_comparator_n_2113), .C0
       (dut_comparator_n_2031), .Y (dut_comparator_n_2004));
  OAI211X1 dut_comparator_g3115(.A0 (dut_comparator_n_2065), .A1
       (dut_comparator_n_2058), .B0 (dut_comparator_n_2068), .C0
       (dut_comparator_n_2008), .Y (dut_comparator_n_2006));
  OA21X1 dut_comparator_g3116(.A0 (dut_comparator_n_2094), .A1
       (dut_comparator_n_2011), .B0 (dut_comparator_n_2085), .Y
       (dut_comparator_n_2007));
  NAND4BXL dut_comparator_g3117(.AN (dut_comparator_n_2094), .B
       (dut_comparator_n_2106), .C (dut_comparator_n_2016), .D
       (dut_comparator_n_2013), .Y (dut_comparator_n_2008));
  AOI211XL dut_comparator_g3118(.A0 (dut_comparator_n_2106), .A1
       (dut_comparator_n_2014), .B0 (dut_comparator_n_2088), .C0
       (dut_comparator_n_2102), .Y (dut_comparator_n_2011));
  OAI22XL dut_comparator_g3119(.A0 (dut_comparator_n_2042), .A1
       (dut_comparator_n_2015), .B0 (dut_comparator_n_2041), .B1
       (dut_comparator_n_2032), .Y (dut_comparator_n_2013));
  AOI32X1 dut_comparator_g3120(.A0 (dut_comparator_n_2112), .A1
       (dut_comparator_n_2040), .A2 (dut_comparator_n_2020), .B0
       (dut_comparator_n_2035), .B1 (dut_comparator_n_2028), .Y
       (dut_comparator_n_2014));
  NAND4XL dut_comparator_g3121(.A (dut_comparator_n_2083), .B
       (dut_comparator_n_2110), .C (dut_comparator_n_2073), .D
       (dut_comparator_n_2022), .Y (dut_comparator_n_2015));
  NOR3BXL dut_comparator_g3122(.AN (dut_comparator_n_2024), .B
       (dut_comparator_n_2109), .C (dut_comparator_n_2091), .Y
       (dut_comparator_n_2016));
  OAI211X1 dut_comparator_g3123(.A0 (dut_comparator_n_2056), .A1
       (dut_comparator_n_2039), .B0 (dut_comparator_n_2083), .C0
       (dut_comparator_n_2043), .Y (dut_comparator_n_2020));
  AOI221X1 dut_comparator_g3124(.A0 (parall_B[0]), .A1
       (dut_comparator_n_2025), .B0 (dut_comparator_n_2082), .B1
       (dut_comparator_n_2071), .C0 (dut_comparator_n_2114), .Y
       (dut_comparator_n_2022));
  NOR2XL dut_comparator_g3125(.A (parall_A[0]), .B
       (dut_comparator_n_2039), .Y (dut_comparator_n_2025));
  OR2X1 dut_comparator_g3126(.A (dut_comparator_n_2074), .B
       (dut_comparator_n_2041), .Y (dut_comparator_n_2028));
  NOR3XL dut_comparator_g3127(.A (dut_comparator_n_2107), .B
       (dut_comparator_n_2089), .C (dut_comparator_n_2065), .Y
       (dut_comparator_n_2024));
  OA21X1 dut_comparator_g3128(.A0 (dut_comparator_n_2105), .A1
       (dut_comparator_n_2112), .B0 (dut_comparator_n_2040), .Y
       (dut_comparator_n_2032));
  OAI211X1 dut_comparator_g3129(.A0 (dut_comparator_n_2104), .A1
       (dut_comparator_n_2110), .B0 (dut_comparator_n_2073), .C0
       (dut_comparator_n_2180), .Y (dut_comparator_n_2035));
  AND3XL dut_comparator_g3130(.A (dut_comparator_n_2108), .B
       (dut_comparator_n_2093), .C (dut_comparator_n_2181), .Y
       (dut_comparator_n_2031));
  INVX1 dut_comparator_g3131(.A (dut_comparator_n_2043), .Y
       (dut_comparator_n_2042));
  OAI21XL dut_comparator_g3132(.A0 (parall_B[1]), .A1
       (dut_comparator_n_2124), .B0 (dut_comparator_n_2071), .Y
       (dut_comparator_n_2039));
  NOR2BX1 dut_comparator_g3133(.AN (dut_comparator_n_2074), .B
       (dut_comparator_n_2104), .Y (dut_comparator_n_2040));
  NAND2XL dut_comparator_g3134(.A (dut_comparator_n_2103), .B
       (dut_comparator_n_2180), .Y (dut_comparator_n_2041));
  NAND3BXL dut_comparator_g3135(.AN (parall_A[2]), .B (parall_B[2]), .C
       (dut_comparator_n_2111), .Y (dut_comparator_n_2043));
  OR2X1 dut_comparator_g3136(.A (dut_comparator_n_2088), .B
       (dut_comparator_n_2066), .Y (dut_comparator_n_2051));
  OAI21XL dut_comparator_g3137(.A0 (dut_comparator_n_2085), .A1
       (dut_comparator_n_2091), .B0 (dut_comparator_n_2113), .Y
       (dut_comparator_n_2053));
  NOR3BXL dut_comparator_g3138(.AN (parall_A[0]), .B (parall_B[0]), .C
       (dut_comparator_n_2082), .Y (dut_comparator_n_2056));
  OA21X1 dut_comparator_g3139(.A0 (dut_comparator_n_2108), .A1
       (dut_comparator_n_2089), .B0 (dut_comparator_n_2093), .Y
       (dut_comparator_n_2058));
  AO21X1 dut_comparator_g3140(.A0 (dut_comparator_n_2107), .A1
       (dut_comparator_n_2093), .B0 (dut_comparator_n_2089), .Y
       (dut_comparator_n_2062));
  NOR2BX1 dut_comparator_g3141(.AN (dut_comparator_n_2102), .B
       (dut_comparator_n_2094), .Y (dut_comparator_n_2066));
  NAND2XL dut_comparator_g3142(.A (dut_comparator_n_2087), .B
       (dut_comparator_n_2092), .Y (dut_comparator_n_2068));
  NAND2BXL dut_comparator_g3144(.AN (dut_comparator_n_2084), .B
       (dut_comparator_n_2092), .Y (dut_comparator_n_2065));
  OA21X1 dut_comparator_g3145(.A0 (parall_B[2]), .A1
       (dut_comparator_n_2131), .B0 (dut_comparator_n_2111), .Y
       (dut_comparator_n_2071));
  NOR2BX1 dut_comparator_g3147(.AN (dut_comparator_n_2103), .B
       (dut_comparator_n_2105), .Y (dut_comparator_n_2073));
  AOI21XL dut_comparator_g3148(.A0 (parall_A[6]), .A1
       (dut_comparator_n_2126), .B0 (dut_comparator_n_2081), .Y
       (dut_comparator_n_2074));
  NOR2BX1 dut_comparator_g3151(.AN (parall_A[7]), .B (parall_B[7]), .Y
       (dut_comparator_n_2081));
  AND2X1 dut_comparator_g3152(.A (dut_comparator_n_2124), .B
       (parall_B[1]), .Y (dut_comparator_n_2082));
  NAND2BXL dut_comparator_g3153(.AN (parall_A[3]), .B (parall_B[3]), .Y
       (dut_comparator_n_2083));
  NOR2BX1 dut_comparator_g3154(.AN (parall_B[14]), .B (parall_A[14]),
       .Y (dut_comparator_n_2084));
  NAND2BXL dut_comparator_g3155(.AN (parall_B[10]), .B (parall_A[10]),
       .Y (dut_comparator_n_2085));
  NOR2BX1 dut_comparator_g3156(.AN (parall_A[14]), .B (parall_B[14]),
       .Y (dut_comparator_n_2087));
  NOR2BX1 dut_comparator_g3157(.AN (parall_A[9]), .B (parall_B[9]), .Y
       (dut_comparator_n_2088));
  NOR2BX1 dut_comparator_g3158(.AN (parall_B[13]), .B (parall_A[13]),
       .Y (dut_comparator_n_2089));
  NAND2BXL dut_comparator_g3159(.AN (parall_B[15]), .B (parall_A[15]),
       .Y (dut_comparator_n_2090));
  NOR2BX1 dut_comparator_g3160(.AN (parall_B[11]), .B (parall_A[11]),
       .Y (dut_comparator_n_2091));
  NAND2BXL dut_comparator_g3161(.AN (parall_A[15]), .B (parall_B[15]),
       .Y (dut_comparator_n_2092));
  NAND2BXL dut_comparator_g3162(.AN (parall_B[13]), .B (parall_A[13]),
       .Y (dut_comparator_n_2093));
  NOR2BX1 dut_comparator_g3163(.AN (parall_B[9]), .B (parall_A[9]), .Y
       (dut_comparator_n_2094));
  NOR2BX1 dut_comparator_g3164(.AN (parall_A[8]), .B (parall_B[8]), .Y
       (dut_comparator_n_2102));
  NAND2BXL dut_comparator_g3165(.AN (parall_A[7]), .B (parall_B[7]), .Y
       (dut_comparator_n_2103));
  NOR2BX1 dut_comparator_g3166(.AN (parall_A[5]), .B (parall_B[5]), .Y
       (dut_comparator_n_2104));
  NOR2BX1 dut_comparator_g3167(.AN (parall_B[5]), .B (parall_A[5]), .Y
       (dut_comparator_n_2105));
  NAND2BXL dut_comparator_g3168(.AN (parall_A[8]), .B (parall_B[8]), .Y
       (dut_comparator_n_2106));
  NOR2BX1 dut_comparator_g3169(.AN (parall_B[12]), .B (parall_A[12]),
       .Y (dut_comparator_n_2107));
  NAND2BXL dut_comparator_g3170(.AN (parall_B[12]), .B (parall_A[12]),
       .Y (dut_comparator_n_2108));
  NOR2BX1 dut_comparator_g3171(.AN (parall_B[10]), .B (parall_A[10]),
       .Y (dut_comparator_n_2109));
  NAND2BXL dut_comparator_g3172(.AN (parall_A[4]), .B (parall_B[4]), .Y
       (dut_comparator_n_2110));
  NAND2BXL dut_comparator_g3173(.AN (parall_B[3]), .B (parall_A[3]), .Y
       (dut_comparator_n_2111));
  NAND2BXL dut_comparator_g3174(.AN (parall_B[4]), .B (parall_A[4]), .Y
       (dut_comparator_n_2112));
  NAND2BXL dut_comparator_g3175(.AN (parall_B[11]), .B (parall_A[11]),
       .Y (dut_comparator_n_2113));
  NOR2XL dut_comparator_g3176(.A (parall_A[6]), .B
       (dut_comparator_n_2126), .Y (dut_comparator_n_2114));
  INVX1 dut_comparator_g3177(.A (parall_A[1]), .Y
       (dut_comparator_n_2124));
  INVX1 dut_comparator_g3178(.A (parall_B[6]), .Y
       (dut_comparator_n_2126));
  INVX1 dut_comparator_g3179(.A (parall_A[2]), .Y
       (dut_comparator_n_2131));
  NAND2BX1 dut_comparator_g2(.AN (dut_comparator_n_2081), .B
       (dut_comparator_n_2114), .Y (dut_comparator_n_2180));
  NOR2BX1 dut_comparator_g3180(.AN (dut_comparator_n_2090), .B
       (dut_comparator_n_2087), .Y (dut_comparator_n_2181));
endmodule

module top(clk_i, res_i, A_i, B_i, out_o, tvalid_i, tready_o);
  input clk_i, res_i, A_i, B_i, tvalid_i;
  output out_o, tready_o;

  wire clk, res, A, B, out, tvalid, tready;

  wire VDDC, VDDO;
  wire VSSC, VSSO;

ALU_top U1 (.clk(clk), 
			.res(res), 
			.A(A), 
			.B(B),
			.out(out), 
			.tvalid(tvalid), 
			.tready(tready));

PADDI PAD_CLK    (.PAD(clk_i), .Y(clk), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADDI PAD_res    (.PAD(res_i), .Y(res), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADDI PAD_tvalid (.PAD(tvalid_i), .Y(tvalid), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADDI PAD_A 	 (.PAD(A_i), .Y(A), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADDI PAD_B 	 (.PAD(B_i), .Y(B), .VDDIOR(VDDO), .VSSIOR(VSSO));

PADDO PAD_out    (.A(out), .PAD(out_o), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADDO PAD_tready (.A(tready), .PAD(tready_o), .VDDIOR(VDDO), .VSSIOR(VSSO));

PADVDD PAD_VDD1 (.VDD(VDDC), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADVDD PAD_VDD2 (.VDD(VDDC), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADVDD PAD_VSS1 (.VSS(VSSC), .VDDIOR(VDDO), .VSSIOR(VSSO));
PADVDD PAD_VSS2 (.VSS(VSSC), .VDDIOR(VDDO), .VSSIOR(VSSO));

PADVDDIOR PAD_VDDIOR (.VDDIOR(VDDO), .VSSIOR(VSSO));
PADVSSIOR PAD_VSSIOR (.VDDIOR(VDDO), .VSSIOR(VSSO));

endmodule
