# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

# Makefile

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

### SOURCES for 3 mark
VERILOG_SOURCES += ../src/osu035_stdcells.v

### SOURCES for 4 mark

### SOURCES for 5 mark

# use VHDL_SOURCES for VHDL files

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file

### HDL for 3 mark
TOPLEVEL = LATCH

### HDL for 4 mark

### HDL for 5 mark

# MODULE is the basename of the Python test file

### Tests for 3 mark
MODULE = testbench_LATCH_easy

### Tests for 4 mark


### Tests for 5 mark


# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
